package tk.programmerjake.peg_parser_generator.eclipse.editors;

import org.eclipse.swt.SWT;
import org.eclipse.swt.graphics.RGB;

public interface IPEGSyntaxHighlightingConstants {
	RGB KEYWORD = new RGB(127, 0, 85);
	int KEYWORD_STYLE = SWT.BOLD;
	RGB RULE_NAME = new RGB(0, 80, 50);
	int RULE_NAME_STYLE = SWT.NORMAL;
	RGB RESULT_VARIABLE = new RGB(0, 0, 192);
	int RESULT_VARIABLE_STYLE = SWT.NORMAL;
	RGB TEMPLATE_VARIABLE = new RGB(100, 70, 50);
	int TEMPLATE_VARIABLE_STYLE = SWT.BOLD;
	RGB OPERATOR = new RGB(0, 0, 0);
	int OPERATOR_STYLE = SWT.NORMAL;
	RGB LINE_COMMENT = new RGB(63, 127, 95);
	int LINE_COMMENT_STYLE = SWT.NORMAL;
	RGB BLOCK_COMMENT = new RGB(63, 127, 95);
	int BLOCK_COMMENT_STYLE = SWT.NORMAL;
	RGB STRING = new RGB(42, 0, 255);
	int STRING_STYLE = SWT.NORMAL;
	RGB CHARACTER_CLASS = new RGB(42, 0, 255);
	int CHARACTER_CLASS_STYLE = SWT.ITALIC;
	RGB CODE = new RGB(100, 40, 128);
	int CODE_STYLE = SWT.BOLD;
	RGB SUBSTITUTION = new RGB(100, 70, 50);
	int SUBSTITUTION_STYLE = SWT.BOLD | SWT.ITALIC;
	RGB CODE_LINE_COMMENT = new RGB(63, 127, 95);
	int CODE_LINE_COMMENT_STYLE = SWT.NORMAL;
	RGB CODE_BLOCK_COMMENT = new RGB(63, 127, 95);
	int CODE_BLOCK_COMMENT_STYLE = SWT.NORMAL;
	RGB CODE_KEYWORD = new RGB(127, 0, 85);
	int CODE_KEYWORD_STYLE = SWT.BOLD;
	RGB CODE_IDENTIFIER = new RGB(0, 0, 0);
	int CODE_IDENTIFIER_STYLE = SWT.NORMAL;
	RGB CODE_STRING = new RGB(42, 0, 255);
	int CODE_STRING_STYLE = SWT.NORMAL;
	RGB CODE_CHAR = new RGB(42, 0, 255);
	int CODE_CHAR_STYLE = SWT.NORMAL;
	RGB CODE_HEADER_NAME = new RGB(42, 0, 255);
	int CODE_HEADER_NAME_STYLE = SWT.NORMAL;
	RGB CODE_NUMBER = new RGB(0, 0, 0);
	int CODE_NUMBER_STYLE = SWT.NORMAL;
	RGB CODE_PUNCTUATOR = new RGB(0, 0, 0);
	int CODE_PUNCTUATOR_STYLE = SWT.NORMAL;
	RGB CODE_UNKNOWN = new RGB(224, 0, 0);
	int CODE_UNKNOWN_STYLE = SWT.BOLD;
}
